name: 'Publish Immutable Action Version'

on:
  push:
    tags:
      # Match version tags, but not the major version tags.
      - 'v[0-9]+.**'

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Publish immutable release
        id: publish
        uses: actions/publish-immutable-action@v0.0.4
